apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jfrog-cloud-demo
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: jfrog-cloud-demo
    spec:
      imagePullSecrets:
      - name: artifactory-docker-registry
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        
        ports:
        - containerPort: {{ .Values.service.internalPort }}
