# Default values for testapi-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository:  39.99.224.184:8082/docker-webinar-virtual/jfrog-cloud-demo
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: jfrog-cloud-demo
  type: NodePort
  externalPort: 80
  nodePort: 30303
  internalPort: 8080
